* Energy Efficiency Planner
A web-based mapping tool. Use it to plan an energy intervention in an area, then share that plan with local stakeholders. Create alternative versions of plans which have been shared with you.
  
** Features
 + Import shapes onto a map by dragging and dropping geoJSON, topoJSON or Shapefile, along with data describing attributes of those shapes as tsv.
 + View the data associated with the shapes in a table.
 + Colour the shapes on the map according to the data.

** Source Code
Get [[https://github.com/cse-bristol/energy-efficiency-planner][the source code]]. 

** Installation
To install, clone the repository then serve using any web server, for example using python3 on a Debian system:
#+BEGIN_SRC sh
  sudo python3 -m http.server 80 &
#+END_SRC

*** Building the Code
If you make changes to the code, you will need to rebuild it. Our Javascript files our arranged as node.js modules, and we use the 'browserify' tool to combine them into a single file.

Begin by installing [[http://nodejs.org/][Node JS]]. On a Debian-based system, I'd recommend using this PPA:
#+BEGIN_SRC sh
sudo add-apt-repository ppa:chris-lea/node.js 
sudo aptitude update
sudo aptitude install -y nodejs
#+END_SRC

Then run the following:
#+BEGIN_SRC sh
  npm -g install browserify # Install Browserify as a command you can run.
  npm install # Install the various packages we depend on (listed in package.json).
  browserify glue.js -o bin/main.js # Package all the Javascript code together in a way that we can load into a browser.
#+END_SRC

** TODO Future Plans
http://tools.smartsteep.eu/wiki/ToDo

